# Generated by Django 6.1.1 on 2026-09-22 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('revised_contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('contract_signing_date', models.DateField(blank=True, null=True)),
                ('commencement_date', models.DateField(blank=True, null=True)),
                ('original_completion_date', models.DateField(blank=True, null=True)),
                ('revised_completion_date', models.DateField(blank=True, null=True)),
                ('contract_duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('performance_security_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('performance_security_expiry', models.DateField(blank=True, null=True)),
                ('advance_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('advance_payment_recovered', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant_org', models.ForeignKey(blank=True, limit_choices_to={'org_type': 'consultant'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_consultant', to='accounts.organization')),
                ('contractor_org', models.ForeignKey(limit_choices_to={'org_type': 'contractor'}, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_contractor', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_date', models.DateField(blank=True, null=True)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionOfTime',
            fields=[
                ('eot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eot_number', models.CharField(max_length=20)),
                ('approved_days', models.PositiveIntegerField()),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions_of_time', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='IPC',
            fields=[
                ('ipc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ipc_number', models.CharField(max_length=20)),
                ('ipc_date', models.DateField(blank=True, null=True)),
                ('certified_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('retention_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipcs', to='contracts.contract')),
            ],
            options={
                'ordering': ['contract', 'ipc_number'],
            },
        ),
        migrations.CreateModel(
            name='VariationOrder',
            fields=[
                ('vo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vo_number', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_orders', to='contracts.contract')),
            ],
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['current_status'], name='contracts_c_current_d5e7f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='extensionoftime',
            unique_together={('contract', 'eot_number')},
        ),
        migrations.AlterUniqueTogether(
            name='ipc',
            unique_together={('contract', 'ipc_number')},
        ),
        migrations.AlterUniqueTogether(
            name='variationorder',
            unique_together={('contract', 'vo_number')},
        ),
    ]
