# Generated by Django 6.1.1 on 2026-10-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
